services:
  nutridietdb:
    image: mongo:6
    container_name: nutridietdb
    # Puertos eliminados para seguridad; solo accesibles internamente
    volumes:
      - nutridiet_data:/data/db
      - ./docker/mongo-init/nutridiet-init.js:/docker-entrypoint-initdb.d/01-init.js:ro
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    restart: unless-stopped
    healthcheck:
      test: >
        mongosh -u ${MONGO_ROOT_USER} -p ${MONGO_ROOT_PASS} --authenticationDatabase admin --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 30s
      retries: 5

  fooddb:
    image: mongo:6
    container_name: fooddb
    ports:
      - "27017:27017" #acuerdate de quitaro despues de generar las imagenes
    # Puertos eliminados para seguridad; solo accesibles internamente
    volumes:
      - fooddb_data:/data/db
      - ./docker/mongo-init/fooddb-init.js:/docker-entrypoint-initdb.d/01-init.js:ro
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    restart: unless-stopped
    healthcheck:
      test: >
        mongosh -u ${MONGO_ROOT_USER} -p ${MONGO_ROOT_PASS} --authenticationDatabase admin --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 30s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nutridiet-backend
    depends_on:
      nutridietdb:
        condition: service_healthy
      fooddb:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./backend/static/images:/app/static/images # Persistencia de fotos descargadas
      - ./backend/static/images_recipies:/app/static/images_recipies # <-- Donde guarda el script
    command: >
      bash -c "./wait-for-it.sh nutridietdb:27017 --timeout=60 -- 
      ./wait-for-it.sh fooddb:27017 --timeout=60 -- 
      uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./nutridiet-app
      dockerfile: Dockerfile
    container_name: nutridiet-frontend
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nutridiet-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/static/images:/app/static/images:ro # Nginx sirve las imágenes directamente
      - ./backend/static/images_recipies:/app/static/images_recipies:ro # Recetas (NUEVO)
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  nutridiet_data:
  fooddb_data: