server {
    listen 80;
    server_name localhost;

    # API -> backend
    location /api/ {
        # Importante: usa el nombre del servicio 'backend'
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend SPA
    location / {
        # Importante: usa el nombre del servicio 'frontend'
        proxy_pass http://frontend:3000/;
        proxy_set_header Host $host;
    }
}